### ISSUE TITLE
heroku.appName by System property

### ISSUE THREAD

**Issue by cbornet** [heroku/heroku-gradle#1]
It would be great to be able to pass the app name by command line
```sh
./gradlew deployHeroku -Dheroku.appName=myapp
```
like with the maven plugin

**Comment by jkutner** [comment]
Fixed by e12e64c33ae52ab36c6431b6b3bccf31f898e6c9. Will be available in 1.0.0

**Comment by asarkar** [comment]
I faced this issue today where the plugin failed to find the app name, although there is an `app.json` present in the project root directory.

**Comment by Malax** [comment]
`app.json` usually does not contain a specific app name this plugin could use to deploy the app. This is the order the plugin tries to resolve the app name in:

- The heroku.properties file
- The heroku.appName system property
- The configuration in Gradle
- The "heroku" Git remote

This could be much better documented, I created #27 to track this. Do you have any of those settings available/configured?

**Comment by asarkar** [comment]
I referred to the [official sample app](https://github.com/heroku/java-getting-started) for Java, and didn't see a `heroku.properties` file. There's an `app.json` though.
