### ISSUE TITLE
Artifact is deployed to Heroku platform under its full filesystem path in Gradle daemon's directory

### ISSUE THREAD

**Issue by dcmoeller** [heroku/heroku-gradle#21]
I'm using Heroku Gradle plugin (version `1.0.4`) to deploy a roughly 13 MB sized executable application JAR.
And struggling with correctly packing only this artifact (and not all the other stuff from Gradle's `build` folder);
and getting the instruction to launch this app right.

## First szenario:

Excerpt from `build.gradle`:

```
heroku {
  appName = '[APPLICATION]'
  processTypes(
          web: "java \$JAVA_OPTS -jar ./build/libs/[APPLICATION].jar" as String
  )
}
```

This works, BUT the artifact uploaded to Heroku platform contains many useless content, e.g. compiled class files etc.:

```
$ ./gradlew deployHeroku

> Task :deployHeroku
-----> Packaging application...
       - app: [APPLICATION]
       - including: build/
-----> Creating build...
       - file: build/heroku/build.tgz
       - size: 66MB
```

66 MB, but application's JAR is only 13 MB in size!

## Second szenario:

Adding `includeBuildDir = false` to heroku task in `build.gradle`:

```
heroku {
  appName = '[APPLICATION]'
  includeBuildDir = false
  processTypes(
          web: "java \$JAVA_OPTS -jar ./build/libs/[APPLICATION].jar" as String
  )
}
```

This FAILS, the artifact uploaded to Heroku platform does NOT contain the executable JAR file!
Size of the uploaded `build.tgz` is simply too small:

```
$ ./gradlew deployHeroku

> Task :deployHeroku
-----> Packaging application...
       - app: [APPLICATION]
       - including: build/
-----> Creating build...
       - file: build/heroku/build.tgz
       - size: 1MB
```

## Third szenario:

Let's exactly define the artifact file to upload using `includes = ["build/libs/[APPLICATION].jar"]` in heroku task:

```
heroku {
  appName = '[APPLICATION]'
  includeBuildDir = false
  includes = ["build/libs/[APPLICATION].jar"]
  processTypes(
          web: "java \$JAVA_OPTS -jar ./build/libs/[APPLICATION].jar" as String
  )
}
```

This FAILS, Heroku's console tells us the reason:

```
Error: Unable to access jarfile ./build/libs/[APPLICATION].jar
```

Size of the uploaded `build.tgz` is OK now (13 MB), BUT what means the over-long `including` path:

```
$ ./gradlew deployHeroku

> Task :deployHeroku
-----> Packaging application...
       - app: [APPLICATION]
       - including: /home/[USER]/.gradle/daemon/6.5.1/build/libs/[APPLICATION].jar
-----> Creating build...
       - file: build/heroku/build.tgz
       - size: 13MB
```

Connecting to the Heroku platform and searching for our application JAR file shows:

```
$ heroku run -a [APPLICATION] -- pwd\; find . -name [APPLICATION]\*.jar
Running pwd; find . -name *.jar on ⬢ [APPLICATION]... up, run.2939 (Free)
/app
./home/[USER]/.gradle/daemon/6.5.1/build/libs/[APPLICATION].jar
```

Oh, my JAR file has been uploaded with its absolute filesystem path of Gradle's daemon!
So changing `processTypes` instruction to contain `./home/[USER]/.gradle/daemon/6.5.1/build/libs/[APPLICATION].jar` would work, but that is not the expected solution!

My expectation is that this operates the same way as with the other two szenarios: Application JAR file is available on Heroku platform under project-relative path `build/libs/[APPLICATION].jar`.

**Comment by Malax** [comment]
Hey @dcmoeller, thanks for the detailed report! I'll investigate and update this issue with my findings.

**Comment by Malax** [comment]
What was your working directory when you encountered the overly long file paths in scenario three? Can you try again while your working directory is the project directory, if not already the case?

**Comment by dcmoeller** [comment]
@Malax: All commands shown are issued in project's directory, the one containing `build.gradle`.

**Comment by Malax** [comment]
I was able to reproduce this when running with my local Gradle installation (i.e. `gradle build deployHeroku`). It works correctly when using the Gradle wrapper from the project (`./gradlew build deployHeroku`). I assume the demon does something that trips off our path resolution code.

Try running the deploy with `gradlew` as a workaround for now. I'll see that we have a fix for this next week.

**Comment by dcmoeller** [comment]
Interesting! I've **not** tried local Gradle installation, I've always used project's Gradle Wrapper `./gradlew ...`.

**Comment by dcmoeller** [comment]
I'm using Gradle version 6.5.1. Here it show that both invocations `gradle deployHeroku` as well as `./gradlew deployHeroku` behave the same!

**Comment by dcmoeller** [comment]
Some more output from my invocations, maybe this helps:

**Comment by dcmoeller** [comment]
```
$ ./gradlew deployHeroku
Executed by Gradle 6.5.1

> Task :deployHeroku
-----> Packaging application...
       - app: [APPLICATION]
       - including: /home/[USER]/.gradle/daemon/6.5.1/build/libs/[APPLICATION].jar
-----> Creating build...
       - file: build/heroku/build.tgz
       - size: 13MB
-----> Uploading build...
       - success
-----> Deploying...
remote: 
remote: -----> heroku-gradle app detected
remote: -----> Installing JDK 14... done
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:        Done: 79.3M
remote: -----> Launching...
[...]
```

Exactly the same output and outcome if using `gradle deployHeroku`.

**Comment by Malax** [comment]
@dcmoeller I started work on a new major version for this plugin which leverages an updated `heroku-deploy` version that does not show this bug. You can track progress in my draft PR #22. I'm hopeful we can get this out of the door this or at least next week.

**Comment by dcmoeller** [comment]
Looking forward :smiley: 
By the way, fixed issue myself by modifying one line from my original post containing `includes:` like this (beware of using absolute path here by using Gradle's `buildDir` path variable):
```
includes = ["${buildDir}/libs/[APPLICATION].jar"]
```
With this you can also modify `processTypes(web ...)` to the following expected version:
```
web: "java \$JAVA_OPTS -jar ./build/libs/[APPLICATION].jar" as String
```
This works.

**Comment by Malax** [comment]
Hey @dcmoeller, `2.0.0` has been released last friday. Can you confirm it resolves your issue? :)

**Comment by dcmoeller** [comment]
Confirmed: My "Third szenario" works now :+1:
To import new version I have to switch the following clause in `build.gradle`:
```groovy
  //classpath 'gradle.plugin.com.heroku.sdk:heroku-gradle:1+'
  classpath 'gradle.plugin.com.heroku.sdk.heroku-gradle:heroku-gradle:2+'
```

**Comment by Malax** [comment]
Thanks for confirming and the initial report! 👍
