### ISSUE TITLE
Where's heroku login?

### ISSUE THREAD

**Issue by asarkar** [heroku/heroku-gradle#25]
Where's `heroku login`? In order to run and deploy from CI, a login is necessary.

**Comment by asarkar** [comment]
Based on [this article](https://devcenter.heroku.com/articles/authentication#api-token-storage), the API key can be set as an environment variable `HEROKU_API_KEY`. It'd be very useful for this to be documented, or for the key to be passed in on the command line.

**Comment by Malax** [comment]
This is much better documented for the [Heroku Maven plugin](https://github.com/heroku/heroku-maven-plugin#heroku-api-key) and works the same for the Gradle plugin. This is not limited to only the api key. I created #27 to track this. Thanks for your report!
