### ISSUE TITLE
Can't Find 'FileUtils' in HerokuPluginExtension

### ISSUE THREAD

**Issue by tdespenza** [heroku/heroku-gradle#3]
_I'm getting this error when using the plugin to deploy to heroku._ 

_`Could not get unknown property 'FileUtils' for object of type com.heroku.sdk.gradle.HerokuPluginExtension.`_

_jHispter 4.1.1_
_Gradle 3.4.1_
_Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:         1.8.0_66 (Oracle Corporation 25.66-b17)
OS:           Mac OS X 10.12_

**Comment by jkutner** [comment]
Fixed in 504a3abe12d684b994cdbe1667d70c470f88939c. Will be available in 1.0.0 (when it's out).
